version: '3.8'

services:
  edu-mall-app:
    build: . #用根目录 Dockerfile 现编
    image: edu-mall:local
    container_name: edu-mall-app
    restart: unless-stopped
    ports:
      - "8090:8089" #宿主8090 -> 容器 8089（避开goland的8089）
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mall_docker.yml:/app/mall_local.yml:ro #配置只读挂进， 不烤进镜像
    networks:
      - mall-net
networks:
  mall-net:
    external: true #复用建好的 已连上infra的那个
