server {
    listen 443 ssl;
    server_name localhost; #任意域名都收，本机测试用

    ssl_certificate /etc/nginx/certs/edu-mall.crt; #公钥证书：发给浏览器验证身份
    ssl_certificate_key /etc/nginx/certs/edu-mall.key; #私钥：留在服务器用于解密，绝不外发

    access_log /var/log/nginx/access.log;

    location / {
        proxy_pass http://edu-mall-app:8089; #转发到compose里的app服务名
        #三个转发头： 让app知道“真正的用户是谁、走的什么协议”
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}