// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newLesson(db *gorm.DB, opts ...gen.DOOption) lesson {
	_lesson := lesson{}

	_lesson.lessonDo.UseDB(db, opts...)
	_lesson.lessonDo.UseModel(&model.Lesson{})

	tableName := _lesson.lessonDo.TableName()
	_lesson.ALL = field.NewAsterisk(tableName)
	_lesson.ID = field.NewInt64(tableName, "id")
	_lesson.Name = field.NewString(tableName, "name")
	_lesson.Detail = field.NewString(tableName, "detail")
	_lesson.CategoryID = field.NewInt64(tableName, "category_id")
	_lesson.VideoKey = field.NewString(tableName, "video_key")
	_lesson.VideoFileName = field.NewString(tableName, "video_file_name")
	_lesson.Duration = field.NewInt32(tableName, "duration")
	_lesson.Attachments = field.NewString(tableName, "attachments")
	_lesson.Chapters = field.NewString(tableName, "chapters")
	_lesson.Status = field.NewInt32(tableName, "status")
	_lesson.CreateAt = field.NewTime(tableName, "create_at")
	_lesson.CreateBy = field.NewInt64(tableName, "create_by")
	_lesson.UpdateAt = field.NewTime(tableName, "update_at")
	_lesson.UpdateBy = field.NewInt64(tableName, "update_by")

	_lesson.fillFieldMap()

	return _lesson
}

// lesson 录播课时表
type lesson struct {
	lessonDo lessonDo

	ALL           field.Asterisk
	ID            field.Int64
	Name          field.String // 课时名
	Detail        field.String // 课时介绍
	CategoryID    field.Int64  // 目录ID
	VideoKey      field.String // 视频文件key
	VideoFileName field.String
	Duration      field.Int32  // 视频时长
	Attachments   field.String // 课时课件文件列表(JSON数组,每项含 file_key/file_name/file_type 字段)
	Chapters      field.String // 课时章节(JSON数组,每项含 id/name/begin_position/end_position 字段)
	Status        field.Int32  // 1：启用  -1：禁用
	CreateAt      field.Time
	CreateBy      field.Int64
	UpdateAt      field.Time
	UpdateBy      field.Int64

	fieldMap map[string]field.Expr
}

func (l lesson) Table(newTableName string) *lesson {
	l.lessonDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lesson) As(alias string) *lesson {
	l.lessonDo.DO = *(l.lessonDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lesson) updateTableName(table string) *lesson {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.Name = field.NewString(table, "name")
	l.Detail = field.NewString(table, "detail")
	l.CategoryID = field.NewInt64(table, "category_id")
	l.VideoKey = field.NewString(table, "video_key")
	l.VideoFileName = field.NewString(table, "video_file_name")
	l.Duration = field.NewInt32(table, "duration")
	l.Attachments = field.NewString(table, "attachments")
	l.Chapters = field.NewString(table, "chapters")
	l.Status = field.NewInt32(table, "status")
	l.CreateAt = field.NewTime(table, "create_at")
	l.CreateBy = field.NewInt64(table, "create_by")
	l.UpdateAt = field.NewTime(table, "update_at")
	l.UpdateBy = field.NewInt64(table, "update_by")

	l.fillFieldMap()

	return l
}

func (l *lesson) WithContext(ctx context.Context) *lessonDo { return l.lessonDo.WithContext(ctx) }

func (l lesson) TableName() string { return l.lessonDo.TableName() }

func (l lesson) Alias() string { return l.lessonDo.Alias() }

func (l lesson) Columns(cols ...field.Expr) gen.Columns { return l.lessonDo.Columns(cols...) }

func (l *lesson) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lesson) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 14)
	l.fieldMap["id"] = l.ID
	l.fieldMap["name"] = l.Name
	l.fieldMap["detail"] = l.Detail
	l.fieldMap["category_id"] = l.CategoryID
	l.fieldMap["video_key"] = l.VideoKey
	l.fieldMap["video_file_name"] = l.VideoFileName
	l.fieldMap["duration"] = l.Duration
	l.fieldMap["attachments"] = l.Attachments
	l.fieldMap["chapters"] = l.Chapters
	l.fieldMap["status"] = l.Status
	l.fieldMap["create_at"] = l.CreateAt
	l.fieldMap["create_by"] = l.CreateBy
	l.fieldMap["update_at"] = l.UpdateAt
	l.fieldMap["update_by"] = l.UpdateBy
}

func (l lesson) clone(db *gorm.DB) lesson {
	l.lessonDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lesson) replaceDB(db *gorm.DB) lesson {
	l.lessonDo.ReplaceDB(db)
	return l
}

type lessonDo struct{ gen.DO }

func (l lessonDo) Debug() *lessonDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonDo) WithContext(ctx context.Context) *lessonDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonDo) ReadDB() *lessonDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonDo) WriteDB() *lessonDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonDo) Session(config *gorm.Session) *lessonDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonDo) Clauses(conds ...clause.Expression) *lessonDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonDo) Returning(value interface{}, columns ...string) *lessonDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonDo) Not(conds ...gen.Condition) *lessonDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonDo) Or(conds ...gen.Condition) *lessonDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonDo) Select(conds ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonDo) Where(conds ...gen.Condition) *lessonDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonDo) Order(conds ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonDo) Distinct(cols ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonDo) Omit(cols ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonDo) Join(table schema.Tabler, on ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonDo) Group(cols ...field.Expr) *lessonDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonDo) Having(conds ...gen.Condition) *lessonDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonDo) Limit(limit int) *lessonDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonDo) Offset(offset int) *lessonDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonDo) Unscoped() *lessonDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonDo) Create(values ...*model.Lesson) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonDo) CreateInBatches(values []*model.Lesson, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonDo) Save(values ...*model.Lesson) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonDo) First() (*model.Lesson, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lesson), nil
	}
}

func (l lessonDo) Take() (*model.Lesson, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lesson), nil
	}
}

func (l lessonDo) Last() (*model.Lesson, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lesson), nil
	}
}

func (l lessonDo) Find() ([]*model.Lesson, error) {
	result, err := l.DO.Find()
	return result.([]*model.Lesson), err
}

func (l lessonDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Lesson, err error) {
	buf := make([]*model.Lesson, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonDo) FindInBatches(result *[]*model.Lesson, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonDo) Attrs(attrs ...field.AssignExpr) *lessonDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonDo) Assign(attrs ...field.AssignExpr) *lessonDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonDo) Joins(fields ...field.RelationField) *lessonDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonDo) Preload(fields ...field.RelationField) *lessonDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonDo) FirstOrInit() (*model.Lesson, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lesson), nil
	}
}

func (l lessonDo) FirstOrCreate() (*model.Lesson, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lesson), nil
	}
}

func (l lessonDo) FindByPage(offset int, limit int) (result []*model.Lesson, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonDo) Delete(models ...*model.Lesson) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonDo) withDO(do gen.Dao) *lessonDo {
	l.DO = *do.(*gen.DO)
	return l
}
