// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newOrderRefund(db *gorm.DB, opts ...gen.DOOption) orderRefund {
	_orderRefund := orderRefund{}

	_orderRefund.orderRefundDo.UseDB(db, opts...)
	_orderRefund.orderRefundDo.UseModel(&model.OrderRefund{})

	tableName := _orderRefund.orderRefundDo.TableName()
	_orderRefund.ALL = field.NewAsterisk(tableName)
	_orderRefund.ID = field.NewInt64(tableName, "id")
	_orderRefund.UserID = field.NewInt64(tableName, "user_id")
	_orderRefund.OrderID = field.NewInt64(tableName, "order_id")
	_orderRefund.ItemIds = field.NewString(tableName, "item_ids")
	_orderRefund.ApplyAt = field.NewInt64(tableName, "apply_at")
	_orderRefund.Reason = field.NewString(tableName, "reason")
	_orderRefund.Status = field.NewInt32(tableName, "status")
	_orderRefund.Amount = field.NewInt64(tableName, "amount")
	_orderRefund.InnerTradeNo = field.NewString(tableName, "inner_trade_no")
	_orderRefund.RefundID = field.NewString(tableName, "refund_id")
	_orderRefund.ApplyUserID = field.NewInt64(tableName, "apply_user_id")
	_orderRefund.DoneAt = field.NewInt64(tableName, "done_at")

	_orderRefund.fillFieldMap()

	return _orderRefund
}

// orderRefund 订单退款记录表
type orderRefund struct {
	orderRefundDo orderRefundDo

	ALL          field.Asterisk
	ID           field.Int64
	UserID       field.Int64
	OrderID      field.Int64
	ItemIds      field.String
	ApplyAt      field.Int64
	Reason       field.String
	Status       field.Int32 // // 0：无退款，1：退款中，2：退款完成，3：退款异常
	Amount       field.Int64
	InnerTradeNo field.String
	RefundID     field.String
	ApplyUserID  field.Int64
	DoneAt       field.Int64 // 处理完成时间

	fieldMap map[string]field.Expr
}

func (o orderRefund) Table(newTableName string) *orderRefund {
	o.orderRefundDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderRefund) As(alias string) *orderRefund {
	o.orderRefundDo.DO = *(o.orderRefundDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderRefund) updateTableName(table string) *orderRefund {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.UserID = field.NewInt64(table, "user_id")
	o.OrderID = field.NewInt64(table, "order_id")
	o.ItemIds = field.NewString(table, "item_ids")
	o.ApplyAt = field.NewInt64(table, "apply_at")
	o.Reason = field.NewString(table, "reason")
	o.Status = field.NewInt32(table, "status")
	o.Amount = field.NewInt64(table, "amount")
	o.InnerTradeNo = field.NewString(table, "inner_trade_no")
	o.RefundID = field.NewString(table, "refund_id")
	o.ApplyUserID = field.NewInt64(table, "apply_user_id")
	o.DoneAt = field.NewInt64(table, "done_at")

	o.fillFieldMap()

	return o
}

func (o *orderRefund) WithContext(ctx context.Context) *orderRefundDo {
	return o.orderRefundDo.WithContext(ctx)
}

func (o orderRefund) TableName() string { return o.orderRefundDo.TableName() }

func (o orderRefund) Alias() string { return o.orderRefundDo.Alias() }

func (o orderRefund) Columns(cols ...field.Expr) gen.Columns { return o.orderRefundDo.Columns(cols...) }

func (o *orderRefund) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderRefund) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 12)
	o.fieldMap["id"] = o.ID
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["order_id"] = o.OrderID
	o.fieldMap["item_ids"] = o.ItemIds
	o.fieldMap["apply_at"] = o.ApplyAt
	o.fieldMap["reason"] = o.Reason
	o.fieldMap["status"] = o.Status
	o.fieldMap["amount"] = o.Amount
	o.fieldMap["inner_trade_no"] = o.InnerTradeNo
	o.fieldMap["refund_id"] = o.RefundID
	o.fieldMap["apply_user_id"] = o.ApplyUserID
	o.fieldMap["done_at"] = o.DoneAt
}

func (o orderRefund) clone(db *gorm.DB) orderRefund {
	o.orderRefundDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderRefund) replaceDB(db *gorm.DB) orderRefund {
	o.orderRefundDo.ReplaceDB(db)
	return o
}

type orderRefundDo struct{ gen.DO }

func (o orderRefundDo) Debug() *orderRefundDo {
	return o.withDO(o.DO.Debug())
}

func (o orderRefundDo) WithContext(ctx context.Context) *orderRefundDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderRefundDo) ReadDB() *orderRefundDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderRefundDo) WriteDB() *orderRefundDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderRefundDo) Session(config *gorm.Session) *orderRefundDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderRefundDo) Clauses(conds ...clause.Expression) *orderRefundDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderRefundDo) Returning(value interface{}, columns ...string) *orderRefundDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderRefundDo) Not(conds ...gen.Condition) *orderRefundDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderRefundDo) Or(conds ...gen.Condition) *orderRefundDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderRefundDo) Select(conds ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderRefundDo) Where(conds ...gen.Condition) *orderRefundDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderRefundDo) Order(conds ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderRefundDo) Distinct(cols ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderRefundDo) Omit(cols ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderRefundDo) Join(table schema.Tabler, on ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderRefundDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderRefundDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderRefundDo) Group(cols ...field.Expr) *orderRefundDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderRefundDo) Having(conds ...gen.Condition) *orderRefundDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderRefundDo) Limit(limit int) *orderRefundDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderRefundDo) Offset(offset int) *orderRefundDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderRefundDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderRefundDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderRefundDo) Unscoped() *orderRefundDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderRefundDo) Create(values ...*model.OrderRefund) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderRefundDo) CreateInBatches(values []*model.OrderRefund, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderRefundDo) Save(values ...*model.OrderRefund) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderRefundDo) First() (*model.OrderRefund, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderRefund), nil
	}
}

func (o orderRefundDo) Take() (*model.OrderRefund, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderRefund), nil
	}
}

func (o orderRefundDo) Last() (*model.OrderRefund, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderRefund), nil
	}
}

func (o orderRefundDo) Find() ([]*model.OrderRefund, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrderRefund), err
}

func (o orderRefundDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderRefund, err error) {
	buf := make([]*model.OrderRefund, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderRefundDo) FindInBatches(result *[]*model.OrderRefund, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderRefundDo) Attrs(attrs ...field.AssignExpr) *orderRefundDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderRefundDo) Assign(attrs ...field.AssignExpr) *orderRefundDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderRefundDo) Joins(fields ...field.RelationField) *orderRefundDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderRefundDo) Preload(fields ...field.RelationField) *orderRefundDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderRefundDo) FirstOrInit() (*model.OrderRefund, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderRefund), nil
	}
}

func (o orderRefundDo) FirstOrCreate() (*model.OrderRefund, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderRefund), nil
	}
}

func (o orderRefundDo) FindByPage(offset int, limit int) (result []*model.OrderRefund, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderRefundDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderRefundDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderRefundDo) Delete(models ...*model.OrderRefund) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderRefundDo) withDO(do gen.Dao) *orderRefundDo {
	o.DO = *do.(*gen.DO)
	return o
}
