// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newPaymentPrivateKey(db *gorm.DB, opts ...gen.DOOption) paymentPrivateKey {
	_paymentPrivateKey := paymentPrivateKey{}

	_paymentPrivateKey.paymentPrivateKeyDo.UseDB(db, opts...)
	_paymentPrivateKey.paymentPrivateKeyDo.UseModel(&model.PaymentPrivateKey{})

	tableName := _paymentPrivateKey.paymentPrivateKeyDo.TableName()
	_paymentPrivateKey.ALL = field.NewAsterisk(tableName)
	_paymentPrivateKey.ID = field.NewInt64(tableName, "id")
	_paymentPrivateKey.PrivateKey = field.NewString(tableName, "private_key")
	_paymentPrivateKey.AppID = field.NewString(tableName, "app_id")

	_paymentPrivateKey.fillFieldMap()

	return _paymentPrivateKey
}

type paymentPrivateKey struct {
	paymentPrivateKeyDo paymentPrivateKeyDo

	ALL        field.Asterisk
	ID         field.Int64
	PrivateKey field.String
	AppID      field.String

	fieldMap map[string]field.Expr
}

func (p paymentPrivateKey) Table(newTableName string) *paymentPrivateKey {
	p.paymentPrivateKeyDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentPrivateKey) As(alias string) *paymentPrivateKey {
	p.paymentPrivateKeyDo.DO = *(p.paymentPrivateKeyDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentPrivateKey) updateTableName(table string) *paymentPrivateKey {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PrivateKey = field.NewString(table, "private_key")
	p.AppID = field.NewString(table, "app_id")

	p.fillFieldMap()

	return p
}

func (p *paymentPrivateKey) WithContext(ctx context.Context) *paymentPrivateKeyDo {
	return p.paymentPrivateKeyDo.WithContext(ctx)
}

func (p paymentPrivateKey) TableName() string { return p.paymentPrivateKeyDo.TableName() }

func (p paymentPrivateKey) Alias() string { return p.paymentPrivateKeyDo.Alias() }

func (p paymentPrivateKey) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentPrivateKeyDo.Columns(cols...)
}

func (p *paymentPrivateKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentPrivateKey) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["private_key"] = p.PrivateKey
	p.fieldMap["app_id"] = p.AppID
}

func (p paymentPrivateKey) clone(db *gorm.DB) paymentPrivateKey {
	p.paymentPrivateKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentPrivateKey) replaceDB(db *gorm.DB) paymentPrivateKey {
	p.paymentPrivateKeyDo.ReplaceDB(db)
	return p
}

type paymentPrivateKeyDo struct{ gen.DO }

func (p paymentPrivateKeyDo) Debug() *paymentPrivateKeyDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentPrivateKeyDo) WithContext(ctx context.Context) *paymentPrivateKeyDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentPrivateKeyDo) ReadDB() *paymentPrivateKeyDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentPrivateKeyDo) WriteDB() *paymentPrivateKeyDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentPrivateKeyDo) Session(config *gorm.Session) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentPrivateKeyDo) Clauses(conds ...clause.Expression) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentPrivateKeyDo) Returning(value interface{}, columns ...string) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentPrivateKeyDo) Not(conds ...gen.Condition) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentPrivateKeyDo) Or(conds ...gen.Condition) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentPrivateKeyDo) Select(conds ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentPrivateKeyDo) Where(conds ...gen.Condition) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentPrivateKeyDo) Order(conds ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentPrivateKeyDo) Distinct(cols ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentPrivateKeyDo) Omit(cols ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentPrivateKeyDo) Join(table schema.Tabler, on ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentPrivateKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentPrivateKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentPrivateKeyDo) Group(cols ...field.Expr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentPrivateKeyDo) Having(conds ...gen.Condition) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentPrivateKeyDo) Limit(limit int) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentPrivateKeyDo) Offset(offset int) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentPrivateKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentPrivateKeyDo) Unscoped() *paymentPrivateKeyDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentPrivateKeyDo) Create(values ...*model.PaymentPrivateKey) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentPrivateKeyDo) CreateInBatches(values []*model.PaymentPrivateKey, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentPrivateKeyDo) Save(values ...*model.PaymentPrivateKey) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentPrivateKeyDo) First() (*model.PaymentPrivateKey, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentPrivateKey), nil
	}
}

func (p paymentPrivateKeyDo) Take() (*model.PaymentPrivateKey, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentPrivateKey), nil
	}
}

func (p paymentPrivateKeyDo) Last() (*model.PaymentPrivateKey, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentPrivateKey), nil
	}
}

func (p paymentPrivateKeyDo) Find() ([]*model.PaymentPrivateKey, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentPrivateKey), err
}

func (p paymentPrivateKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentPrivateKey, err error) {
	buf := make([]*model.PaymentPrivateKey, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentPrivateKeyDo) FindInBatches(result *[]*model.PaymentPrivateKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentPrivateKeyDo) Attrs(attrs ...field.AssignExpr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentPrivateKeyDo) Assign(attrs ...field.AssignExpr) *paymentPrivateKeyDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentPrivateKeyDo) Joins(fields ...field.RelationField) *paymentPrivateKeyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentPrivateKeyDo) Preload(fields ...field.RelationField) *paymentPrivateKeyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentPrivateKeyDo) FirstOrInit() (*model.PaymentPrivateKey, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentPrivateKey), nil
	}
}

func (p paymentPrivateKeyDo) FirstOrCreate() (*model.PaymentPrivateKey, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentPrivateKey), nil
	}
}

func (p paymentPrivateKeyDo) FindByPage(offset int, limit int) (result []*model.PaymentPrivateKey, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentPrivateKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentPrivateKeyDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentPrivateKeyDo) Delete(models ...*model.PaymentPrivateKey) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentPrivateKeyDo) withDO(do gen.Dao) *paymentPrivateKeyDo {
	p.DO = *do.(*gen.DO)
	return p
}
