// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newUserCart(db *gorm.DB, opts ...gen.DOOption) userCart {
	_userCart := userCart{}

	_userCart.userCartDo.UseDB(db, opts...)
	_userCart.userCartDo.UseModel(&model.UserCart{})

	tableName := _userCart.userCartDo.TableName()
	_userCart.ALL = field.NewAsterisk(tableName)
	_userCart.ID = field.NewInt64(tableName, "id")
	_userCart.UserID = field.NewInt64(tableName, "user_id")
	_userCart.GoodsID = field.NewInt64(tableName, "goods_id")
	_userCart.Quantity = field.NewInt32(tableName, "quantity")
	_userCart.AddAt = field.NewTime(tableName, "add_at")

	_userCart.fillFieldMap()

	return _userCart
}

// userCart 用户购物车
type userCart struct {
	userCartDo userCartDo

	ALL      field.Asterisk
	ID       field.Int64
	UserID   field.Int64
	GoodsID  field.Int64
	Quantity field.Int32
	AddAt    field.Time

	fieldMap map[string]field.Expr
}

func (u userCart) Table(newTableName string) *userCart {
	u.userCartDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userCart) As(alias string) *userCart {
	u.userCartDo.DO = *(u.userCartDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userCart) updateTableName(table string) *userCart {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.GoodsID = field.NewInt64(table, "goods_id")
	u.Quantity = field.NewInt32(table, "quantity")
	u.AddAt = field.NewTime(table, "add_at")

	u.fillFieldMap()

	return u
}

func (u *userCart) WithContext(ctx context.Context) *userCartDo { return u.userCartDo.WithContext(ctx) }

func (u userCart) TableName() string { return u.userCartDo.TableName() }

func (u userCart) Alias() string { return u.userCartDo.Alias() }

func (u userCart) Columns(cols ...field.Expr) gen.Columns { return u.userCartDo.Columns(cols...) }

func (u *userCart) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userCart) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["goods_id"] = u.GoodsID
	u.fieldMap["quantity"] = u.Quantity
	u.fieldMap["add_at"] = u.AddAt
}

func (u userCart) clone(db *gorm.DB) userCart {
	u.userCartDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userCart) replaceDB(db *gorm.DB) userCart {
	u.userCartDo.ReplaceDB(db)
	return u
}

type userCartDo struct{ gen.DO }

func (u userCartDo) Debug() *userCartDo {
	return u.withDO(u.DO.Debug())
}

func (u userCartDo) WithContext(ctx context.Context) *userCartDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userCartDo) ReadDB() *userCartDo {
	return u.Clauses(dbresolver.Read)
}

func (u userCartDo) WriteDB() *userCartDo {
	return u.Clauses(dbresolver.Write)
}

func (u userCartDo) Session(config *gorm.Session) *userCartDo {
	return u.withDO(u.DO.Session(config))
}

func (u userCartDo) Clauses(conds ...clause.Expression) *userCartDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userCartDo) Returning(value interface{}, columns ...string) *userCartDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userCartDo) Not(conds ...gen.Condition) *userCartDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userCartDo) Or(conds ...gen.Condition) *userCartDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userCartDo) Select(conds ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userCartDo) Where(conds ...gen.Condition) *userCartDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userCartDo) Order(conds ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userCartDo) Distinct(cols ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userCartDo) Omit(cols ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userCartDo) Join(table schema.Tabler, on ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userCartDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userCartDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userCartDo) RightJoin(table schema.Tabler, on ...field.Expr) *userCartDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userCartDo) Group(cols ...field.Expr) *userCartDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userCartDo) Having(conds ...gen.Condition) *userCartDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userCartDo) Limit(limit int) *userCartDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userCartDo) Offset(offset int) *userCartDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userCartDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userCartDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userCartDo) Unscoped() *userCartDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userCartDo) Create(values ...*model.UserCart) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userCartDo) CreateInBatches(values []*model.UserCart, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userCartDo) Save(values ...*model.UserCart) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userCartDo) First() (*model.UserCart, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCart), nil
	}
}

func (u userCartDo) Take() (*model.UserCart, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCart), nil
	}
}

func (u userCartDo) Last() (*model.UserCart, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCart), nil
	}
}

func (u userCartDo) Find() ([]*model.UserCart, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserCart), err
}

func (u userCartDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCart, err error) {
	buf := make([]*model.UserCart, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userCartDo) FindInBatches(result *[]*model.UserCart, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userCartDo) Attrs(attrs ...field.AssignExpr) *userCartDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userCartDo) Assign(attrs ...field.AssignExpr) *userCartDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userCartDo) Joins(fields ...field.RelationField) *userCartDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userCartDo) Preload(fields ...field.RelationField) *userCartDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userCartDo) FirstOrInit() (*model.UserCart, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCart), nil
	}
}

func (u userCartDo) FirstOrCreate() (*model.UserCart, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCart), nil
	}
}

func (u userCartDo) FindByPage(offset int, limit int) (result []*model.UserCart, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userCartDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userCartDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userCartDo) Delete(models ...*model.UserCart) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userCartDo) withDO(do gen.Dao) *userCartDo {
	u.DO = *do.(*gen.DO)
	return u
}
