// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseCatalog = "course_catalog"

// CourseCatalog 课程目录表
type CourseCatalog struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID int64     `gorm:"column:parent_id;not null;default:-1" json:"parent_id"`
	Level    int32     `gorm:"column:level;not null;default:1" json:"level"`
	Name     string    `gorm:"column:name;not null" json:"name"`
	CourseID int64     `gorm:"column:course_id;not null" json:"course_id"`
	Sort     int32     `gorm:"column:sort;not null" json:"sort"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName CourseCatalog's table name
func (*CourseCatalog) TableName() string {
	return TableNameCourseCatalog
}
