// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLessonCategory = "lesson_category"

// LessonCategory 录播课时目录表
type LessonCategory struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Level    int32  `gorm:"column:level;not null" json:"level"`
	Sort     int32  `gorm:"column:sort;not null" json:"sort"`
	ParentID int64  `gorm:"column:parent_id;not null;default:-1" json:"parent_id"`
}

// TableName LessonCategory's table name
func (*LessonCategory) TableName() string {
	return TableNameLessonCategory
}
