// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLesson = "lessons"

// Lesson 录播课时表
type Lesson struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string `gorm:"column:name;not null;comment:课时名" json:"name"`                // 课时名
	Detail        string `gorm:"column:detail;not null;comment:课时介绍" json:"detail"`           // 课时介绍
	CategoryID    int64  `gorm:"column:category_id;not null;comment:目录ID" json:"category_id"` // 目录ID
	VideoKey      string `gorm:"column:video_key;not null;comment:视频文件key" json:"video_key"`  // 视频文件key
	VideoFileName string `gorm:"column:video_file_name;not null" json:"video_file_name"`
	Duration      int32  `gorm:"column:duration;not null;comment:视频时长" json:"duration"`                                                               // 视频时长
	Attachments   string `gorm:"column:attachments;not null;comment:课时课件文件列表[{"file_key": "", "file_name": "", "file_type": ""}]" json:"attachments"` // 课时课件文件列表[{"file_key": "", "file_name": "", "file_type": ""}]
	/*
		[{
		  "id": "dddd",
		   "name": "dddd",
		   "begin_position": 1,
		   "end_position": 1
		}]
	*/
	Chapters string    `gorm:"column:chapters;not null;comment:[{\n  "id": "dddd",\n   "name": "dddd",\n   "begin_position": 1,\n   "end_position": 1\n}]" json:"chapters"`
	Status   int32     `gorm:"column:status;not null;comment:1：启用  -1：禁用" json:"status"` // 1：启用  -1：禁用
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Lesson's table name
func (*Lesson) TableName() string {
	return TableNameLesson
}
