// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePaymentPrivateKey = "payment_private_key"

// PaymentPrivateKey mapped from table <payment_private_key>
type PaymentPrivateKey struct {
	ID         int64  `gorm:"column:id;primaryKey" json:"id"`
	PrivateKey string `gorm:"column:private_key;not null" json:"private_key"`
	AppID      string `gorm:"column:app_id;not null" json:"app_id"`
}

// TableName PaymentPrivateKey's table name
func (*PaymentPrivateKey) TableName() string {
	return TableNamePaymentPrivateKey
}
