// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCart = "user_cart"

// UserCart 用户购物车
type UserCart struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID   int64     `gorm:"column:user_id;primaryKey" json:"user_id"`
	GoodsID  int64     `gorm:"column:goods_id;not null" json:"goods_id"`
	Quantity int32     `gorm:"column:quantity;not null;default:1" json:"quantity"`
	AddAt    time.Time `gorm:"column:add_at;not null" json:"add_at"`
}

// TableName UserCart's table name
func (*UserCart) TableName() string {
	return TableNameUserCart
}
